CREATE OR REPLACE TRIGGER trg_running_trip_insert
AFTER INSERT ON RUNNING_TRIP
FOR EACH ROW
BEGIN
    UPDATE AVAILABILITY
    SET IS_AVAILABLE = 0, LAST_UPDATED = CURRENT_TIMESTAMP
    WHERE D_ID = :NEW.D_ID;
    
END;
/

CREATE OR REPLACE TRIGGER trg_running_trip_delete
BEFORE DELETE ON RUNNING_TRIP
FOR EACH ROW
BEGIN
    UPDATE AVAILABILITY
    SET IS_AVAILABLE = 1, LAST_UPDATED = CURRENT_TIMESTAMP
    WHERE D_ID = :OLD.D_ID;
    
END;
/
