CREATE or REPLACE PROCEDURE DRIVER_AVAIL_INSERT IS

BEGIN
	FOR R IN (SELECT ID FROM DRIVER WHERE NOT EXISTS(SELECT D_ID FROM AVAILABILITY WHERE D_ID=ID))
	LOOP
	INSERT INTO AVAILABILITY(D_ID,IS_AVAILABLE,LAST_UPDATED) VALUES(R.ID,0,CURRENT_TIMESTAMP);

	 
END LOOP;
END;


