CREATE or REPLACE TRIGGER dv_vehicle 
after UPDATE 
of PLATE_NO
on DRIVER
for each ROW

BEGIN

	

DELETE FROM VEHICLE WHERE PLATE_NO=:old.PLATE_NO;



end;

drop TRIGGER dv_vehicle

SELECT * from VEHICLE WHERE PLATE_NO='DHA-GA-791212'






SELECT 
        V.ID VID,
        V.PLATE_NO PNO,
        V.MODELNAME MNAME,
        V.PLAN_ID PID,
        M.V_TYPE TYPE,
        M.MANUFACTURER COMPANY,
				D.ID AS DID,
				D.NAME AS DNAME
    FROM 
        VEHICLE V JOIN MODEL M
        ON(UPPER(V.MODELNAME)=UPPER(M.NAME))
				JOIN DRIVER D 
				ON V.PLATE_NO=D.PLATE_NO
    WHERE
        V.PLATE_NO=:plate




SELECT * from DRIVER WHERE phone='8801420420420'

SELECT ID,GETIMAGEOFDRIVER(ID) AS IMAGE
    FROM  DRIVER
    WHERE ID= GETDRIVERIDFROMPLATE('KHU-THA-458943');
		
		
		
		DECLARE
		
		BEGIN
		DBMS_OUTPUT.PUT_LINE(GETDRIVERIDFROMPLATE('KHU-THA-458943'));
		END;
		
		
		SELECT ID,GETIMAGEOFDRIVER(ID) AS IMAGE
    FROM  DRIVER
    WHERE plate_no='KHU-THA-458943';
		
		SELECT ID,GETDRIVERIDFROMPLATE('KHU-THA-458943      ') from DRIVER WHERE PLATE_NO='KHU-THA-458943';
		SELECT ID,GETDRIVERIDFROMPLATE(PLATE_NO),PLATE_NO from DRIVER WHERE PLATE_NO='KHU-THA-458943';
		
		
		SELECT * from VEHICLE_LOG
SELECT * from MODEl


SELECT * FROM VEHICLE WHERE PLATE_NO='KHU-THA-458942';
SELECT * from MODEl
SELECT * from VEHICLE

SELECT * from VEHICLE_log




ALTER TABLE VEHICLE
drop constraint VEHICLE_MODEL_FK;

ALTER TABLE MODEL 
drop constraint MODEL_PK;

DECLARE

BEGIN

for R in (SELECT NAME,V_TYPE,MANUFACTURER from MODEL)
LOOP
	UPDATE MODEL set name=UPPER(name),V_TYPE=UPPER(V_TYPE),MANUFACTURER=UPPER(MANUFACTURER)
	WHERE NAME=R.name;
END LOOP;


end;
/

ALTER TABLE model
ADD CONSTRAINT pk_model_name PRIMARY KEY (name);



SELECT * FROM VEHICLE


DECLARE

BEGIN

for R in (SELECT MODELNAME,plate_no from VEHICLE)
LOOP
	UPDATE VEHICLE set modelname=UPPER(MODELNAME),PLATE_NO=UPPER(PLATE_NO) WHERE PLATE_NO=R.PLATE_NO;
END LOOP;


end;
/

ALTER TABLE VEHICLE
add 	constraint vehicle_model_fk Foreign key(modelname) references model(name) ;


-- SELECT name,count(*) from MODEl GROUP BY name ORDER BY count(*) desc
-- SELECT * from MODel
-- INSERT INTO MODEL(name,V_TYPE,MANUFACTURER) VALUES('axio','car','toYota')

SELECT * from TRIP_HISTORY WHERE TRIM(PLATE_NO)='DHA-THA-201919'