SELECT count(DISTINCT id) from DRIVER
WHERE
(
    (TO_CHAR(phone) LIKE '88017%' OR
    TO_CHAR(phone) LIKE '88018%' OR
TO_CHAR(phone) LIKE '88016%' OR
TO_CHAR(phone) LIKE '88015%' OR
TO_CHAR(phone) LIKE '88013%' OR
TO_CHAR(phone) LIKE '88014%' OR
    TO_CHAR(phone) LIKE '88019%')
		AND (LENGTH(TO_CHAR(phone))=13)
);

SELECT lengthTO_CHAR(PHONE) FROM DRIVER;

SELECT round(lat,4),round(lng,4) from DRIVER WHERE id=287;

DELETE from TRIP_REQUEST where USERNAME='';

SELECT * FROM TRIP_REQUEST WHERE id=85


SELECT * FROM RUNNING_TRIP ORDER BY TIME_REQUEST desc;

SELECT * from TRIP_HISTORY

drop TRIGGER DELETE_OLD_DATA

DELETE from RUNNING_TRIP

SELECT * FROM USERS

SELECT * from AVAILABILITY ORDER BY LAST_UPDATED desc


SELECT 
         TR_ID, 
         D_ID, 
         USERNAME,
         TIME_REQUEST,
         PLAT,
         PLNG,
        DLAT,
        DLNG

    FROM 
        RUNNING_TRIP
        WHERE  USERNAME='aelves4' AND NOTIFIED=1
        ORDER BY TIME_REQUEST DESC


SELECT * FROM DRIVER WHERE UPPER(NAME) like 'MIRZA%';


INSERT INTO availability (d_id, is_available, last_updated)
  VALUES (1061, 0, CURRENT_TIMESTAMP);

SELECT * from AVAILABILITY ORDER BY LAST_UPDATED desc


drop TRIGGER insert_driver_availability


SELECT * from MODEL WHERE V_TYPE='CNG'


INSERT INTO AVAILABILITY(d_id,IS_AVAILABLE,LAST_UPDATED)



UPDATE AVAILABILITY
    SET IS_AVAILABLE = 0, LAST_UPDATED = CURRENT_TIMESTAMP
    WHERE D_ID = 1061;
		
		SELECT * FROM AVAILABILITY WHERE D_ID=1061

drop TRIGGER "RIDE"."INSERT_INTO_AVAILABILITY"



SELECT * from TRIP_REQUEST;
SELECT * FROM RUNNING_TRIP;
SELECT * from TRIP_HISTORY;

DELETE from RUNNING_TRIP


DELETE from TRIP_REQUEST
delete from TRIP_HISTORY

SELECT * from DRIVER



UPDATE WALLET set BALANCE=10000 WHERE id=381

SELECT TRANSACTION_NO,AMOUNT,convert_to_gmt6(PAYMENT_TIME) from PAYMENTS



SELECT constraint_name
FROM user_constraints
WHERE table_name = 'TRIP_HISTORY'
 AND column_name = 'FINISH_TIME';
  AND constraint_type = 'NOT NULL';

SELECT constraint_name
FROM user_cons_columns
WHERE table_name = 'TRIP_HISTORY'
  AND column_name = 'FINISH_TIME';
	
	
	
	SYS_C008277


SELECT * from TRIP_HISTORY ORDER BY FINISH_TIME desc




INSERT INTO
    REVIEW(RATING,DESCRIPTION,TR_ID)
    VALUES(2,'bhalo',231)




SELECT * FROM TRIP_HISTORY

SELECT 
T.PLATE_NO AS PLATE_NO,
SUM(RATING)/COUNT(DISTINCT R.ID) AS AVG_RATING
FROM TRIP_HISTORY T NATURAL JOIN REVIEW R
WHERE PLATE_NO=(SELECT PLATE_NO FROM DRIVER WHERE ID=295)
GROUP BY T.PLATE_NO












SELECT 
T.PLATE_NO AS PLATE_NO,
SUM(R.RATING)/COUNT(DISTINCT R.ID) AS AVG_RATING
FROM TRIP_HISTORY T NATURAL JOIN REVIEW R
WHERE T.PLATE_NO=(SELECT PLATE_NO FROM DRIVER WHERE ID=295)
GROUP BY T.PLATE_NO


SELECT * from TRIP_HISTORY






SELECT 
        TR_ID,
        TRANSACTION_NO,
        AMOUNT,
        CONVERT_TO_GMT6(PAYMENT_TIME) AS WHEN

    FROM 
        payments
        NATURAL join (SELECT tr_id from TRIP_HISTORY WHERE username='shania_aisharja');









SELECT * from TRIP_HISTORY WHERE USERNAME='shania_aisharja'



DELETE from TRIP_HISTORY WHERE FINISH_TIME is NULL;





SELECT * FROM DRIVER



SELECT count(DISTINCT CONCAT(lat, lng)) from DRIVER

SELECT count(DISTINCT CONCAT(ROUND(lat,1),ROUND(lng,1))) from DRIVER


SELECT COUNT(DISTINCT CONCAT(ROUND(LAT, 1), ROUND(LNG, 1))) FROM DRIVER





UPDATE DRIVER set IMAGE='user3.jpeg' WHERE name='Kaium'

SELECT * from DRIVER WHERE IMAGE is not null


SELECT * from TRIP_HISTORY ORDER BY tr_id desc


SELECT * from VEHICLE V where 
MODELNAME IN
(
SELECT name from MODEL
WHERE
UPPER(V_TYPE)='BIKE' and UPPER(MANUFACTURER)='YAMAHA'
)

UPDATE USERS set u


UPPER(SELECT V_TYPE from MODEL M WHERE M.name=V.modelname)='BIKE'




UPDATE



SELECT * from VEHICLE v join MODEL M
on v.MODELNAME=m.NAME
WHERE upper(m.v_type)='BIKE' and INITCAP(MANUFACTURER)='Yamaha'




