CREATE OR REPLACE TRIGGER delete_old_data
BEFORE INSERT ON RUNNING_TRIP
FOR EACH ROW
BEGIN
  IF :NEW.timestamp_column < SYSTIMESTAMP - INTERVAL '1' HOUR THEN
    DELETE FROM TRIP_REQUEST WHERE timestamp_column < SYSTIMESTAMP - INTERVAL '1' HOUR;
  END IF;
END;
/


